=== gokulsam07/checkly/src/test/resources/data/api/dashboard/create-response-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "expandChecks": {
      "type": "boolean"
    },
    "favicon": {
      "type": "string"
    },
    "showHeader": {
      "type": "boolean"
    },
    "link": {
      "type": "string"
    },
    "paginate": {
      "type": "boolean"
    },
    "description": {
      "type": "string"
    },
    "isPrivate": {
      "type": "boolean"
    },
    "showP99": {
      "type": "boolean"
    },
    "useTagsAndOperator": {
      "type": "boolean"
    },
    "checksPerPage": {
      "type": "integer"
    },
    "customUrl": {
      "type": "string"
    },
    "refreshRate": {
      "type": "integer"
    },
    "showP95": {
      "type": "boolean"
    },
    "width": {
      "type": "string"
    },
    "header": {
      "type": "string"
    },
    "enableIncidents": {
      "type": "boolean"
    },
    "paginationRate": {
      "type": "integer"
    },
    "hideTags": {
      "type": "boolean"
    },
    "tags": {
      "type": "array",
      "items": {}
    },
    "customCSS": {
      "type": "string"
    },
    "keys": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "maskedKey": {
              "type": "string"
            },
            "rawKey": {
              "type": "string"
            },
            "created_at": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "maskedKey",
            "rawKey",
            "created_at"
          ]
        }
      ]
    },
    "created_at": {
      "type": "string"
    },
    "dashboardId": {
      "type": "string"
    },
    "id": {
      "type": "integer"
    }
  }
}

=== gokulsam07/checkly/src/test/resources/data/api/dashboard/update-dashboard.json
{
        "width": "FULL",
        "refreshRate": 60,
        "paginate": true,
        "paginationRate": 60,
        "checksPerPage": 15,
        "useTagsAndOperator": false,
        "hideTags": false,
        "enableIncidents": false,
        "expandChecks": false,
        "showHeader": true,
        "isPrivate": false,
        "showP95": true,
        "showP99": true,
        "description": "Edited the description to test"
   }

=== gokulsam07/checkly/src/test/resources/data/api/create-dashboard.json
{
  "width": "FULL",
  "refreshRate": 60,
  "paginate": true,
  "paginationRate": 60,
  "checksPerPage": 15,
  "useTagsAndOperator": false,
  "hideTags": false,
  "enableIncidents": false,
  "expandChecks": false,
  "showHeader": true,
  "isPrivate": false,
  "showP95": true,
  "showP99": true,
  "customUrl": "gsam07",
  "favicon": "https://www.flaticon.com/free-icon/github-logo_25231",
  "link": "https://github.com/gokulsam07/checkly",
  "header": "Gokul's Dashboard",
  "description": "Sample dashboard created for automation check"
}
